const fs = require('fs');
const valores = require("../coline/values_manager.js");
const tablaTipos= require("../coline/tablaTipos.js");
class traducir{
    constructor()
    {
        this.init();
        this.salida=valores.getEtiqueta();
        this.getcmpstringequal();
        this.getpotencia();
        this.getraizsq();
        this.getpotene();
        this.getImprimirCad();
        this.getConcatenar();
        this.getReverse();
        this.getftoa();
        this.getintToStr();
        this.getent();
        this.getbooltoStr();
        this.getStringToNum();
        this.save("var p=0;\nvar h=0;\n");
        
    }
    init()
    {
        //this.cadena=this.getReverse()+this.getImprimirCad()+this.getConcatenar()+"var p=0;\nvar h=0;\n"+this.cadena;
        fs.writeFileSync("./codigo3d", "");
    }

    save(cad)
    {
        fs.appendFileSync("./codigo3d",cad);
    }
    imprimirHead(cadena)
    {
        this.save(cadena+"\n");
    }
    imprimir(cadena)
    {
        var c="       "+cadena+"\n";
        this.save(c);
        //console.log(c);
    }
    imprimir_L(cadena)
    {
        var c="   "+cadena+"\n";
        this.save(c);
        //console.log(c);
    }
    comentarioSimple(cadena)
    {
        var c="//"+cadena+"\n";
        //this.save(c);
        //console.log(c);
    }
    comentario(cadena)
    {
        var c="/*########    "+cadena+"    ########*/"+"\n";
        //this.save(c);
        //console.log(c);
    }  

    getcmpstringequal()
    {        
        var Linicio=valores.getEtiqueta();var lv=valores.getEtiqueta();var lf=valores.getEtiqueta();
        var lv2=valores.getEtiqueta();var lf2=valores.getEtiqueta();var fin=valores.getEtiqueta();
        var lx1=valores.getEtiqueta();
        var taw1=valores.getTemporal();var h1=valores.getTemporal();var h2=valores.getTemporal();
        var taw2=valores.getTemporal();var tb1=valores.getTemporal();var tb2=valores.getTemporal();
        this.save("void cmpIgual(){\n");
        this.save("        "+taw1+"=p+1;\n");
        this.save("        "+h1+"=stack["+taw1+"];\n");
        this.save("        "+taw2+"=p+2;\n");
        this.save("        "+h2+"=stack["+taw2+"];\n");
        this.save("        stack[p]=0;\n");
        this.save("    "+Linicio+":\n");
        this.save("        "+tb1+"=heap["+h1+"];\n");        
        this.save("        "+tb2+"=heap["+h2+"];\n");
        this.save("        if("+tb1+"=="+tablaTipos.fin_cadena+") goto "+lx1+";\n");
        this.save("        goto "+lf+";\n");
        this.save("    "+lx1+":\n");
        this.save("        if ("+tb2+"=="+tablaTipos.fin_cadena+") goto "+lv+";\n");
        this.save("        goto "+lf+";\n");
        this.save("    "+lv+":\n");
        this.save("        stack[p]=1;\n");
        this.save("        goto "+fin+";\n");
        this.save("    "+lf+":\n");
        this.save("        if ("+tb1+"=="+tablaTipos.fin_cadena+") goto "+lv2+";\n");
        this.save("        if ("+tb2+"=="+tablaTipos.fin_cadena+") goto "+lv2+";\n");
        this.save("        if ("+tb1+"!="+tb2+") goto "+lv2+";\n");
        this.save("        goto "+lf2+";\n");
        this.save("    "+lv2+":\n");
        this.save("        goto "+fin+";\n");
        this.save("    "+lf2+":\n");
        this.save("        "+h1+"="+h1+"+1;\n");
        this.save("        "+h2+"="+h2+"+1;\n");
        this.save("        goto "+Linicio+";\n");
        this.save("    "+fin+":\n");
        this.save("}\n");

    }
    getStringToNum()
    {
        var taux=valores.getTemporal();var apuntador=valores.getTemporal();
        var entero=valores.getTemporal();var decimal=valores.getTemporal();
        var dec=valores.getTemporal();var signo=valores.getTemporal();
        var bandera=valores.getTemporal();
        var tx1=valores.getTemporal();var t2=valores.getTemporal();
        var t3=valores.getTemporal();var t4=valores.getTemporal();
        var t5=valores.getTemporal();var t6=valores.getTemporal();
        var t7=valores.getTemporal();var t8=valores.getTemporal();

        var taf=valores.getTemporal();var tf=valores.getTemporal();var tac=valores.getTemporal();
        var tc=valores.getTemporal();
        var Linicio=valores.getEtiqueta();var next1=valores.getEtiqueta();var next2=valores.getEtiqueta();
        var next3=valores.getEtiqueta();var next4=valores.getEtiqueta();var salidaif=valores.getEtiqueta();
        var salida=valores.getEtiqueta();var lf=valores.getEtiqueta();
        this.save("void StringToNum(){\n");
        this.save("        "+taux+"=p+1;\n");
        this.save("        "+apuntador+"=stack["+taux+"];\n");
        this.save("        "+entero+"=0;\n");
        this.save("        "+decimal+"=0;\n");
        this.save("        "+dec+"=10;\n");
        this.save("        "+signo+"=1;\n");
        this.save("        "+bandera+"=1;\n");
        this.save("    "+Linicio+":\n");
        this.save("        "+tx1+"=heap["+apuntador+"];\n");
        this.save("        if ("+tx1+"=="+tablaTipos.fin_cadena+") goto "+salida+";\n");
        this.save("        if ("+tx1+"!=45) goto "+next1+";\n");
        this.save("        "+signo+"=-1;\n");
        this.save("        goto "+salidaif+";\n");
        this.save("    "+next1+":\n");
        this.save("        if("+tx1+"!=46) goto "+next2+";\n");
        this.save("        "+bandera+"=0;\n");
        this.save("        goto "+salidaif+";\n");
        this.save("    "+next2+":\n");
        this.save("        if("+tx1+">=58) goto "+lf+";\n");
        this.save("        if("+tx1+">47) goto "+next3+";\n");
        this.save("    "+lf+":\n");
        this.save("        print(\"%c\",99);\n");
        this.save("        print(\"%c\",97);\n");
        this.save("        print(\"%c\",115);\n");
        this.save("        print(\"%c\",116);\n");
        this.save("        print(\"%c\",32);\n");
        this.save("        print(\"%c\",101);\n");
        this.save("        print(\"%c\",114);\n");
        this.save("        print(\"%c\",114);\n");
        this.save("        print(\"%c\",111);\n");
        this.save("        print(\"%c\",114);\n");
        this.save("        print(\"%c\",32);\n");
        this.save("        "+taf+"=p+2;\n");
        this.save("        "+tf+"=stack["+taf+"];\n");
        this.save("        "+tac+"=p+3;\n");
        this.save("        "+tc+"=stack["+tac+"];\n");
        this.save("        print(\"%e\","+tf+");\n");
        this.save("        print(\"%c\",44);\n");
        this.save("        print(\"%e\","+tc+");\n");
        this.save("        goto "+this.salida+";\n");
        this.save("    "+next3+":\n");
        this.save("        if("+bandera+"!=1) goto "+next4+";\n");
        this.save("        "+t2+"="+entero+"*10;\n");
        this.save("        "+t3+"="+t2+"+"+tx1+";\n");
        this.save("        "+t4+"="+t3+"-48;\n");
        this.save("        "+entero+"="+t4+";\n");
        this.save("        goto "+salidaif+";\n");
        this.save("    "+next4+":\n");
        this.save("        "+t5+"="+tx1+"-48;\n");
        this.save("        "+t6+"="+t5+"/"+dec+";\n");
        this.save("        "+t7+"="+decimal+"+"+t6+";\n");
        this.save("        "+decimal+"="+t7+";\n");
        this.save("        "+dec+"="+dec+"*10;\n");
        this.save("    "+salidaif+":\n");
        this.save("        "+apuntador+"="+apuntador+"+1;\n");
        this.save("        goto "+Linicio+";\n");
        this.save("    "+salida+":\n");
        this.save("        "+t8+"="+entero+"+"+decimal+";\n");
        this.save("        "+entero+"="+t8+"*"+signo+";\n");
        this.save("        stack[p]="+entero+";\n");
        this.save("}\n");
    }
    getraizsq()
    {
        var t1=valores.getTemporal();var t2=valores.getTemporal();
        var t3=valores.getTemporal();var t4=valores.getTemporal();
        var t5=valores.getTemporal();var t6=valores.getTemporal();
        var t7=valores.getTemporal();var t8=valores.getTemporal();
        var t9=valores.getTemporal();var t10=valores.getTemporal();
        var t11=valores.getTemporal();var t12=valores.getTemporal();
        var t13=valores.getTemporal();var t14=valores.getTemporal();
        var t15=valores.getTemporal();var t16=valores.getTemporal();
        var t17=valores.getTemporal();var t18=valores.getTemporal();
        var t19=valores.getTemporal();var t20=valores.getTemporal();
        var t21=valores.getTemporal();var t22=valores.getTemporal();
        var t23=valores.getTemporal();var t24=valores.getTemporal();
        var t25=valores.getTemporal();
        /*var l1=valores.getEtiqueta();*/var l2=valores.getEtiqueta();
        var l3=valores.getEtiqueta();var l4=valores.getEtiqueta();
        var l5=valores.getEtiqueta();var l6=valores.getEtiqueta();
        var l7=valores.getEtiqueta();
        this.save("void raizsqrt(){\n");
        this.save("        "+t1+"=p+3;\n");
        this.save("        stack["+t1+"]=0;\n");
        this.save("        "+t2+"=p+4;\n");
        this.save("        stack["+t2+"]=0.00001;\n");
        this.save("        "+t3+"=p+2;\n");
        this.save("        "+t4+"=stack["+t3+"];\n");
        this.save("        if ("+t4+"==0) goto "+l3+";\n");
        this.save("        goto "+l4+";\n");
        this.save("    "+l3+":\n");
        this.save("        "+t5+"=p+3;\n");
        this.save("        stack["+t5+"]=1;\n");
        this.save("        goto "+l2+";\n");
        this.save("    "+l4+":\n");
        this.save("    "+l5+":\n");
        this.save("        "+t6+"=p+6;\n");
        this.save("        "+t7+"="+t6+"+1;\n");
        this.save("        "+t8+"=p+3;\n");
        this.save("        "+t9+"=stack["+t8+"];\n");
        this.save("        stack["+t7+"]="+t9+";\n");
        this.save("        "+t10+"="+t6+"+2;\n");
        this.save("        "+t11+"=p+2;\n");
        this.save("        "+t12+"=stack["+t11+"];\n");
        this.save("        stack["+t10+"]="+t12+";\n");
        this.save("        p=p+6;\n");
        this.save("        call potene();\n");
        this.save("        "+t13+"=p+0;\n");
        this.save("        "+t14+"=stack["+t13+"];\n");
        this.save("        p=p-6;\n");
        this.save("        "+t15+"=p+1;\n");
        this.save("        "+t16+"=stack["+t15+"];\n");
        this.save("        if("+t14+"<"+t16+") goto "+l6+";\n");
        this.save("        goto "+l7+";\n");
        this.save("    "+l6+":\n");
        this.save("        "+t17+"=p+3;\n");
        this.save("        "+t18+"=p+3;\n");
        this.save("        "+t19+"=stack["+t18+"];\n");
        this.save("        "+t20+"=p+4;\n");
        this.save("        "+t21+"=stack["+t20+"];\n");
        this.save("        "+t22+"="+t19+"+"+t21+";\n");
        this.save("        stack["+t17+"]="+t22+";\n");
        this.save("        goto "+l5+";\n");
        this.save("    "+l7+":\n");
        this.save("    "+l2+":\n");
        this.save("        "+t23+"=p+0;\n");
        this.save("        "+t24+"=p+3;\n");
        this.save("        "+t25+"=stack["+t24+"];\n");
        this.save("        stack["+t23+"]="+t25+";\n");
        this.save("}\n");
        

    }

    getpotene()
    {
        var t1=valores.getTemporal();var t2=valores.getTemporal();
        var t3=valores.getTemporal();var t4=valores.getTemporal();
        var t5=valores.getTemporal();var t6=valores.getTemporal();
        var t7=valores.getTemporal();var t8=valores.getTemporal();
        var t9=valores.getTemporal();var t10=valores.getTemporal();
        var t11=valores.getTemporal();var t12=valores.getTemporal();
        var t13=valores.getTemporal();var t14=valores.getTemporal();
        var t15=valores.getTemporal();var t16=valores.getTemporal();
        var t17=valores.getTemporal();var t18=valores.getTemporal();
        var t19=valores.getTemporal();var l2=valores.getEtiqueta();
        var l3=valores.getEtiqueta();var l4=valores.getEtiqueta();
        this.save("void potene(){\n");
        this.save("        "+t1+"=p+3;\n");
        this.save("        stack["+t1+"]=1;\n");
        this.save("        "+t2+"=p+4;\n");
        this.save("        stack["+t2+"]=0;\n");
        this.save("    "+l2+":\n");
        this.save("        "+t3+"=p+4;\n");
        this.save("        "+t4+"=stack["+t3+"];\n");
        this.save("        "+t5+"=p+2;\n");
        this.save("        "+t6+"=stack["+t5+"];\n");
        this.save("        if ("+t4+"<"+t6+") goto "+l3+";\n");
        this.save("        goto "+l4+";\n");
        this.save("    "+l3+":\n");
        this.save("        "+t7+"=p+3;\n");
        this.save("        "+t8+"=p+3;\n");
        this.save("        "+t9+"=stack["+t8+"];\n");
        this.save("        "+t10+"=p+1;\n");
        this.save("        "+t11+"=stack["+t10+"];\n");
        this.save("        "+t12+"="+t9+"*"+t11+";\n");
        this.save("        stack["+t7+"]="+t12+";\n");
        this.save("        "+t13+"=p+4;\n");
        this.save("        "+t14+"=p+4;\n");
        this.save("        "+t15+"=stack["+t14+"];\n");
        this.save("        "+t16+"="+t15+"+1;\n");
        this.save("        stack["+t13+"]="+t16+";\n");
        this.save("        goto "+l2+";\n");
        this.save("    "+l4+":\n");
        this.save("        "+t17+"=p+0;\n");
        this.save("        "+t18+"=p+3;\n");
        this.save("        "+t19+"=stack["+t18+"];\n");
        this.save("        stack["+t17+"]="+t19+";\n");
        this.save("}\n");

    }
    getpotencia()
    {
        var t1=valores.getTemporal();var t2=valores.getTemporal();
        var t3=valores.getTemporal();var t4=valores.getTemporal();
        var t5=valores.getTemporal();var t6=valores.getTemporal();
        var t7=valores.getTemporal();var t8=valores.getTemporal();
        var t9=valores.getTemporal();var t10=valores.getTemporal();
        var t11=valores.getTemporal();var t12=valores.getTemporal();
        var t13=valores.getTemporal();var t14=valores.getTemporal();
        var t15=valores.getTemporal();var t16=valores.getTemporal();
        var t17=valores.getTemporal();var t18=valores.getTemporal();
        var t19=valores.getTemporal();var t20=valores.getTemporal();
        var t21=valores.getTemporal();var t22=valores.getTemporal();
        var t23=valores.getTemporal();var t24=valores.getTemporal();
        var t25=valores.getTemporal();var t26=valores.getTemporal();
        var t27=valores.getTemporal();var t28=valores.getTemporal();var t29=valores.getTemporal();
        var t30=valores.getTemporal();var t31=valores.getTemporal();var t32=valores.getTemporal();
        var t33=valores.getTemporal();var t34=valores.getTemporal();var t35=valores.getTemporal();
        var t36=valores.getTemporal();var t37=valores.getTemporal();var t38=valores.getTemporal();
        var t39=valores.getTemporal();var t40=valores.getTemporal();var t41=valores.getTemporal();
        var t42=valores.getTemporal();var t43=valores.getTemporal();var t44=valores.getTemporal();
        var t45=valores.getTemporal();var t46=valores.getTemporal();var t47=valores.getTemporal();
        var t48=valores.getTemporal();var t49=valores.getTemporal();var t50=valores.getTemporal();
        var t51=valores.getTemporal();var t52=valores.getTemporal();
        var t53=valores.getTemporal();var t54=valores.getTemporal();
        var t55=valores.getTemporal();var t56=valores.getTemporal();
        var t57=valores.getTemporal();var t58=valores.getTemporal();
        var t59=valores.getTemporal();var t60=valores.getTemporal();
        var t61=valores.getTemporal();var t62=valores.getTemporal();
        var t63=valores.getTemporal();var t64=valores.getTemporal();
        var t65=valores.getTemporal();var t66=valores.getTemporal();
        var t67=valores.getTemporal();var t68=valores.getTemporal();
        var t69=valores.getTemporal();var t70=valores.getTemporal();
        var t71=valores.getTemporal();var t72=valores.getTemporal();
        var l1=valores.getEtiqueta();var l2=valores.getEtiqueta();
        var l3=valores.getEtiqueta();var l4=valores.getEtiqueta();
        var l5=valores.getEtiqueta();var l6=valores.getEtiqueta();
        var l7=valores.getEtiqueta();var l8=valores.getEtiqueta();
        var l9=valores.getEtiqueta();var l10=valores.getEtiqueta();
        var l11=valores.getEtiqueta();var l12=valores.getEtiqueta();
        var l13=valores.getEtiqueta();
        this.save("void potencia(){\n");
        this.save("        "+t1+"=p+3;\n");
        this.save("        "+t2+"=p+1;\n");
        this.save("        "+t3+"=stack["+t2+"];\n");
        this.save("        stack["+t1+"]="+t3+";\n");
        this.save("        "+t4+"=p+4;\n");
        this.save("        "+t5+"=p+6;\n");
        this.save("        "+t6+"="+t5+"+1;\n");
        this.save("        "+t7+"=p+2;\n");
        this.save("        "+t8+"=stack["+t7+"];\n");
        this.save("        stack["+t6+"]="+t8+";\n");
        this.save("        p=p+6;\n");
        this.save("        call getent();\n");
        this.save("        "+t9+"=p+0;\n");
        this.save("        "+t10+"=stack["+t9+"];\n");
        this.save("        p=p-6;\n");
        this.save("        stack["+t4+"]="+t10+";\n");
        this.save("        "+t11+"=p+5;\n");
        this.save("        "+t12+"=p+2;\n");
        this.save("        "+t13+"=stack["+t12+"];\n");
        this.save("        "+t14+"=p+4;\n");
        this.save("        "+t15+"=stack["+t14+"];\n");
        this.save("        "+t16+"="+t13+"-"+t15+";\n");
        this.save("        stack["+t11+"]="+t16+";\n");
        this.save("        "+t17+"=p+4;\n");
        this.save("        "+t18+"=stack["+t17+"];\n");
        this.save("        if ("+t18+"==0) goto "+l3+";\n");
        this.save("        goto "+l4+";\n");
        this.save("    "+l3+":\n");
        this.save("        "+t19+"=p+3;\n");
        this.save("        stack["+t19+"]=1;\n");
        this.save("        goto "+l2+";\n");
        this.save("    "+l4+":\n");
        this.save("        "+t20+"=p+6;\n");
        this.save("        stack["+t20+"]=0;\n");
        this.save("    "+l5+":\n");
        this.save("        "+t21+"=p+6;\n");
        this.save("        "+t22+"=stack["+t21+"];\n");
        this.save("        "+t23+"=p+4;\n");
        this.save("        "+t24+"=stack["+t23+"];\n");
        this.save("        "+t25+"="+t24+"-1;\n");
        this.save("        if ("+t22+"<"+t25+") goto "+l6+";\n");
        this.save("        goto "+l7+";\n");
        this.save("    "+l6+":\n");
        this.save("        "+t26+"=p+3;\n");
        this.save("        "+t27+"=p+3;\n");
        this.save("        "+t28+"=stack["+t27+"];\n");
        this.save("        "+t29+"=p+1;\n");
        this.save("        "+t30+"=stack["+t29+"];\n");
        this.save("        "+t31+"="+t28+"*"+t30+";\n");
        this.save("        stack["+t26+"]="+t31+";\n");
        this.save("        "+t32+"=p+6;\n");
        this.save("        "+t33+"=p+6;\n");
        this.save("        "+t34+"=stack["+t33+"];\n");
        this.save("        "+t35+"="+t34+"+1;\n");
        this.save("        stack["+t32+"]="+t35+";\n");
        this.save("        goto "+l5+";\n");
        this.save("    "+l7+":\n");
        this.save("    "+l2+":\n");
        this.save("        "+t36+"=p+6;\n");
        this.save("        stack["+t36+"]=1;\n");
        this.save("        "+t37+"=p+7;\n");
        this.save("        stack["+t37+"]=1;\n");
        this.save("        "+t38+"=p+5;\n");
        this.save("        "+t39+"=stack["+t38+"];\n");
        this.save("        if ("+t39+"!=0) goto "+l9+";\n");
        this.save("        goto "+l10+";\n");
        this.save("    "+l9+":\n");
        this.save("    "+l11+":\n");
        this.save("        "+t40+"=p+5;\n");
        this.save("        "+t41+"=stack["+t40+"];\n");
        this.save("        "+t42+"="+t41+"%1;\n");
        this.save("        if ("+t42+"!=0) goto "+l12+";\n");
        this.save("        goto "+l13+";\n");
        this.save("    "+l12+":\n");
        this.save("        "+t43+"=p+5;\n");
        this.save("        "+t44+"=p+5;\n");
        this.save("        "+t45+"=stack["+t44+"];\n");
        this.save("        "+t46+"="+t45+"*10;\n");
        this.save("        stack["+t43+"]="+t46+";\n");
        this.save("        "+t47+"=p+6;\n");
        this.save("        "+t48+"=p+6;\n");
        this.save("        "+t49+"=stack["+t48+"];\n");
        this.save("        "+t50+"=10*"+t49+";\n");
        this.save("        stack["+t47+"]="+t50+";\n");
        this.save("        goto "+l11+";\n");
        this.save("    "+l13+":\n");
        this.save("        "+t51+"=p+7;\n");
        this.save("        "+t52+"=p+9;\n");
        this.save("        "+t53+"="+t52+"+1;\n");
        this.save("        "+t54+"=p+1;\n");
        this.save("        "+t55+"=stack["+t54+"];\n");
        this.save("        stack["+t53+"]="+t55+";\n");
        this.save("        "+t56+"="+t52+"+2;\n");
        this.save("        "+t57+"=p+6;\n");
        this.save("        "+t58+"=stack["+t57+"];\n");
        this.save("        "+t59+"=p+5;\n");
        this.save("        "+t60+"=stack["+t59+"];\n");
        this.save("        "+t61+"="+t58+"/"+t60+";\n");
        this.save("        stack["+t56+"]="+t61+";\n");
        this.save("        p=p+9;\n");
        this.save("        call raizsqrt();\n");
        this.save("        "+t62+"=p+0;\n");
        this.save("        "+t63+"=stack["+t62+"];\n");
        this.save("        p=p-9;\n");
        this.save("        stack["+t51+"]="+t63+";\n");
        this.save("        goto "+l8+";\n");
        this.save("    "+l10+":\n");
        this.save("    "+l8+":\n");
        this.save("        "+t64+"=p+3;\n");
        this.save("        "+t65+"=p+3;\n");
        this.save("        "+t66+"=stack["+t65+"];\n");
        this.save("        "+t67+"=p+7;\n");
        this.save("        "+t68+"=stack["+t67+"];\n");
        this.save("        "+t69+"="+t66+"*"+t68+";\n");
        this.save("        stack["+t64+"]="+t69+";\n");
        this.save("        "+t70+"=p+0;\n");
        this.save("        "+t71+"=p+3;\n");
        this.save("        "+t72+"=stack["+t71+"];\n");
        this.save("        stack["+t70+"]="+t72+";\n");        
        this.save("}\n");

    }
    
    getbooltoStr()
    {
        var ta=valores.getTemporal();var tval=valores.getTemporal();
        var lf=valores.getEtiqueta();var lsalida=valores.getEtiqueta();
        this.save("void booltostr(){\n");
        //this.save("{\n");
        this.save("        "+ta+"=p+1;\n");
        this.save("        "+tval+"=stack["+ta+"];\n");
        this.save("        stack[p]=h;\n");
        this.save("        if("+tval+"==0)goto "+lf+";\n");
        this.save("        heap[h]=116;\n");
        this.save("        h=h+1;\n");
        this.save("        heap[h]=114;\n");
        this.save("        h=h+1;\n");
        this.save("        heap[h]=117;\n");
        this.save("        h=h+1;\n");
        this.save("        heap[h]=101;\n");
        this.save("        h=h+1;\n");
        this.save("        heap[h]="+tablaTipos.fin_cadena+";\n");
        this.save("        h=h+1;\n");
        this.save("        goto "+lsalida+";\n");
        this.save("    "+lf+":\n");
        this.save("        heap[h]=102;\n");
        this.save("        h=h+1;\n");
        this.save("        heap[h]=97;\n");
        this.save("        h=h+1;\n");
        this.save("        heap[h]=108;\n");
        this.save("        h=h+1;\n");
        this.save("        heap[h]=115;\n");
        this.save("        h=h+1;\n");
        this.save("        heap[h]=101;\n");
        this.save("        h=h+1;\n");
        this.save("        heap[h]="+tablaTipos.fin_cadena+";\n");
        this.save("        h=h+1;\n");
        this.save("    "+lsalida+":\n");
        this.save("}\n");
    }
    getImprimirCad()
    {
        this.save("void print_olcp2jjps(){\n");
        //this.save("{\n");
        var t1=valores.getTemporal();
        this.save("        "+t1+"=p+1;\n");
        var t2=valores.getTemporal();
        this.save("        "+t2+"=stack["+t1+"];\n");
        var inicio=valores.getEtiqueta();
        this.save("    "+inicio+":\n");
        var t3=valores.getTemporal();
        this.save("        "+t3+"=heap["+t2+"];\n");
        var salida=valores.getEtiqueta();
        this.save("        if("+t3+"=="+tablaTipos.fin_cadena+") goto "+salida+";\n");
        this.save("        print(\"%c\","+t3+");\n");
        this.save("        "+t2+"="+t2+"+1;\n");
        this.save("        goto "+inicio+";\n");
        this.save("    "+salida+":\n");
        this.save("}\n");

    }

    getConcatenar()
    {
        var inicio=valores.getEtiqueta();
        var salida=valores.getEtiqueta();
        var t1=valores.getTemporal();
        var t2=valores.getTemporal();
        var t3=valores.getTemporal();
        this.save("void copia_olcp2jjps(){\n");
        this.save("        "+t1+"=p+1;\n");
        this.save("        "+t2+"=stack["+t1+"];\n");
        this.save("    "+inicio+":\n");
        this.save("        "+t3+"=heap["+t2+"];\n");
        this.save("        if("+t3+"=="+tablaTipos.fin_cadena+") goto "+salida+";\n");
        this.save("        heap[h]="+t3+";\n");
        this.save("        h=h+1;"+"\n");
        this.save("        "+t2+"="+t2+"+1;\n");
        this.save("        goto "+inicio+";\n");
        this.save("    "+salida+":\n");
        this.save("}\n");
        var t11=valores.getTemporal();
        var t12=valores.getTemporal();
        var t13=valores.getTemporal();
        var t14=valores.getTemporal();
        var t15=valores.getTemporal();
        var t16=valores.getTemporal();
        this.save("void concat_olcp2jjps(){\n");
        this.save("        stack[p]=h;\n");
        this.save("        "+t11+"=p+3;\n");
        this.save("        "+t12+"="+t11+"+1;\n");
        this.save("        "+t13+"=p+1;\n");
        this.save("        "+t14+"=stack["+t13+"];\n");
        this.save("        stack["+t12+"]="+t14+";\n");
        this.save("        p=p+3;\n");
        this.save("        call copia_olcp2jjps();\n");
        this.save("        p=p-3;\n");
        this.save("        "+t15+"=p+2;\n");
        this.save("        "+t16+"=stack["+t15+"];\n");
        this.save("        stack["+t12+"]="+t16+";\n");
        this.save("        p=p+3;\n");
        this.save("        call copia_olcp2jjps();\n");
        this.save("        p=p-3;\n");
        this.save("        heap[h]="+tablaTipos.fin_cadena+";\n");
        this.save("        h=h+1;\n");
        this.save("}\n");
    }

    getReverse()
    {
        var l3=valores.getEtiqueta();var lt=valores.getEtiqueta();
        var l4=valores.getEtiqueta();
        var tex=valores.getTemporal();var tpu=valores.getTemporal();
        var t1=valores.getTemporal();var t2=valores.getTemporal();
        var t3=valores.getTemporal();var t4=valores.getTemporal();
        var t5=valores.getTemporal();var t6=valores.getTemporal();
        var t7=valores.getTemporal();var t8=valores.getTemporal();
        this.save("void reverse(){\n");
        this.save("        "+tex+"=p+1;\n");
        this.save("        "+tpu+"=stack["+tex+"];\n");
        this.save("        "+t1+"=0;\n");
        this.save("        "+t2+"=0;\n");
        this.save("        "+t3+"=p+2;\n");
        this.save("        "+t4+"=stack["+t3+"];\n");
        this.save("        "+t5+"="+t4+"-1;\n");
        this.save("    "+l3+":\n");
        this.save("        if("+t2+"<"+t5+") goto "+lt+";\n");
        this.save("        goto "+l4+";\n");
        this.save("    "+lt+":\n");
        this.save("        "+t6+"="+tpu+"+"+t2+";\n");
        this.save("        "+t1+"=heap["+t6+"];\n");
        this.save("        "+t7+"="+tpu+"+"+t5+";\n");
        this.save("        "+t8+"=heap["+t7+"];\n");
        this.save("        heap["+t6+"]="+t8+";\n");
        this.save("        heap["+t7+"]="+t1+";\n");
        this.save("        "+t2+"="+t2+"+1;\n");
        this.save("        "+t5+"="+t5+"-1;\n");
        this.save("        goto "+l3+";\n");
        this.save("    "+l4+":\n");
        this.save("}\n");
    }
    getent()
    {
        var t1=valores.getTemporal();var t2=valores.getTemporal();
        var t3=valores.getTemporal();var t4=valores.getTemporal();
        var t5=valores.getTemporal();var t6=valores.getTemporal();
        var t7=valores.getTemporal();var t8=valores.getTemporal();
        var t9=valores.getTemporal();var t10=valores.getTemporal();
        var t11=valores.getTemporal();var t12=valores.getTemporal();
        var t13=valores.getTemporal();var t14=valores.getTemporal();
        var t15=valores.getTemporal();var t16=valores.getTemporal();
        var t17=valores.getTemporal();var t18=valores.getTemporal();
        var t19=valores.getTemporal();var t20=valores.getTemporal();
        var t21=valores.getTemporal();var t22=valores.getTemporal();
        var t23=valores.getTemporal();var t24=valores.getTemporal();
        var t25=valores.getTemporal();var t26=valores.getTemporal();
        var t27=valores.getTemporal();var t28=valores.getTemporal();
        var t29=valores.getTemporal();var t30=valores.getTemporal();
        var t31=valores.getTemporal();var t32=valores.getTemporal();
        var t33=valores.getTemporal();var t34=valores.getTemporal();
        var t35=valores.getTemporal();var t36=valores.getTemporal();
        var t37=valores.getTemporal();var t38=valores.getTemporal();
        var t39=valores.getTemporal();var t40=valores.getTemporal();
        var t41=valores.getTemporal();var t42=valores.getTemporal();
        var t43=valores.getTemporal();var t44=valores.getTemporal();
        /*var l1=valores.getEtiqueta();*/var l2=valores.getEtiqueta();
        var l3=valores.getEtiqueta();var l4=valores.getEtiqueta();
        var l5=valores.getEtiqueta();var l6=valores.getEtiqueta();
        var l7=valores.getEtiqueta();var l8=valores.getEtiqueta();
        var l9=valores.getEtiqueta();var l10=valores.getEtiqueta();
        var l11=valores.getEtiqueta();var l12=valores.getEtiqueta();
       
        this.save("void getent(){\n");
        this.save("        "+t1+"=p+2;\n");
        this.save("        stack["+t1+"]=0;\n");
        this.save("        "+t2+"=p+1;\n");
        this.save("        "+t3+"=stack["+t2+"];\n");
        this.save("        if("+t3+"<0) goto "+l3+" ;\n");
        this.save("        goto "+l4+";\n");
        this.save("    "+l3+":\n");
        this.save("        "+t4+"=p+1;\n");
        this.save("        "+t5+"=p+1;\n");
        this.save("        "+t6+"=stack["+t5+"];\n");
        this.save("        "+t7+"="+t6+"-0.00000000001;\n");
        this.save("        stack["+t4+"]="+ t7+";\n");
        this.save("        "+t8+"=p+3;\n");
        this.save("        "+t9+"=p+1;\n");
        this.save("        "+t10+"=stack["+t9+"];\n");
        this.save("        "+t11+"=0-1;\n");
        this.save("        "+t12+"="+t10+"*"+t11+";\n");
        this.save("        stack["+t8+"]="+t12+";\n");
        this.save("    "+l5+":\n");
        this.save("        "+t13+"=p+3;\n");
        this.save("        "+t14+"=stack["+t13+"];\n");
        this.save("        if("+t14+"<=1) goto "+l6+";\n");
        this.save("        goto "+l7+";\n");
        this.save("    "+l7+":\n");
        this.save("        "+t15+"=p+3;\n");
        this.save("        "+t16+"=p+3;\n");
        this.save("        "+t17+"=stack["+t16+"];\n");
        this.save("        "+t18+"="+t17+"-1;\n");
        this.save("        stack["+t15+"]="+t18+";\n");
        this.save("        "+t19+"=p+2;\n");
        this.save("        "+t20+"=p+2;\n");
        this.save("        "+t21+"=stack["+t20+"];\n");
        this.save("        "+t22+"="+t21+"+1;\n");
        this.save("        stack["+t19+"]="+t22+";\n");
        this.save("        goto "+l5+";\n");
        this.save("    "+l6+":\n");
        this.save("        goto "+l2+";\n");
        this.save("    "+l4+":\n");
        this.save("        "+t23+"=p+1;\n");
        this.save("        "+t24+"=stack["+t23+"];\n");
        this.save("        if ("+t24+">0) goto "+l8+";\n");
        this.save("        goto "+l9+";\n");
        this.save("    "+l8+":\n");
        this.save("        "+t25+"=p+1;\n");
        this.save("        "+t26+"=p+1;\n");
        this.save("        "+t27+"=stack["+t26+"];\n");
        this.save("        "+t28+"="+t27+"+0.00000000001;\n");
        this.save("        stack["+t25+"]="+t28+";\n");
        this.save("        "+t29+"=p+4;\n");
        this.save("        "+t30+"=p+1;\n");
        this.save("        "+t31+"=stack["+t30+"];\n");
        this.save("        stack["+t29+"]="+t31+";\n");
        this.save("    "+l10+":\n");
        this.save("        "+t32+"=p+4;\n");
        this.save("        "+t33+"=stack["+t32+"];\n");
        this.save("        if("+t33+"<=1) goto "+l11+";\n");
        this.save("        goto "+l12+";\n");
        this.save("    "+l12+":\n");
        this.save("        "+t34+"=p+4;\n");
        this.save("        "+t35+"=p+4;\n");
        this.save("        "+t36+"=stack["+t35+"];\n");
        this.save("        "+t37+"="+t36+"-1;\n");
        this.save("        stack["+t34+"]="+t37+";\n");
        this.save("        "+t38+"=p+2;\n");
        this.save("        "+t39+"=p+2;\n");
        this.save("        "+t40+"=stack["+t39+"];\n");
        this.save("        "+t41+"="+t40+"+1;\n");
        this.save("        stack["+t38+"]="+t41+";\n");
        this.save("        goto "+l10+";\n");
        this.save("    "+l11+":\n");
        this.save("        goto "+l2+";\n");
        this.save("    "+l9+":\n");
        this.save("    "+l2+":\n");
        this.save("        "+t42+"=p+0;\n");
        this.save("        "+t43+"=p+2;\n");
        this.save("        "+t44+"=stack["+t43+"];\n");
        this.save("        stack["+t42+"]="+t44+";\n");
        this.save("}\n");
    }
    getintToStr()
    {
      
        var t2=valores.getTemporal();var t3=valores.getTemporal();var t4=valores.getTemporal();
        var t5=valores.getTemporal();var t6=valores.getTemporal();var t8=valores.getTemporal();
        var t9=valores.getTemporal();var t11=valores.getTemporal();var t12=valores.getTemporal();
        var t13=valores.getTemporal();var t14=valores.getTemporal();var t15=valores.getTemporal();
        var t17=valores.getTemporal();var t18=valores.getTemporal();var t19=valores.getTemporal();
        var t20=valores.getTemporal();var t21=valores.getTemporal();var t22=valores.getTemporal();
        var t23=valores.getTemporal();var t24=valores.getTemporal();var t25=valores.getTemporal();
        var t26=valores.getTemporal();var t27=valores.getTemporal();var t28=valores.getTemporal();
        var t29=valores.getTemporal();var t30=valores.getTemporal();var t32=valores.getTemporal();
        var t33=valores.getTemporal();var t34=valores.getTemporal();var t35=valores.getTemporal();
        var t36=valores.getTemporal();var t37=valores.getTemporal();var t38=valores.getTemporal();
        var t39=valores.getTemporal();var t40=valores.getTemporal();var t43=valores.getTemporal();
        var t44=valores.getTemporal();var t45=valores.getTemporal();        
        var l3=valores.getEtiqueta();var l4=valores.getEtiqueta();var l5=valores.getEtiqueta();var l6=valores.getEtiqueta();
        var l7=valores.getEtiqueta();var l8=valores.getEtiqueta();
        
        this.save("void inttostr(){\n");
        this.save("        "+t2+"=p+3;\n");
        this.save("        stack["+t2+"]=h"+";\n");
        this.save("        "+t3+"=p+4;\n");
        this.save("        stack["+t3+"]=0;\n");
        this.save("    "+l3+":\n");
        this.save("        "+t4+"=p+1;\n");
        this.save("        "+t5+"=stack["+t4+"];\n");
        this.save("        if ("+t5+"!=0) goto "+l4+";\n");
        this.save("        goto "+l5+";\n");
        this.save("    "+l4+":\n");
        this.save("        "+t6+"=p+4;\n");
        this.save("        "+t8+"=stack["+t6+"];\n");
        this.save("        "+t9+"="+t8+"+1;\n");
        this.save("        stack["+t6+"]="+t9+";\n");
        this.save("        "+t11+"=p+1;\n");
        this.save("        "+t12+"=stack["+t11+"];\n");
        this.save("        "+t13+"="+t12+"%10;\n");
        this.save("        "+t14+"="+t13+"+48;\n");
        this.save("        heap[h]="+t14+";\n");
        this.save("        h=h+1;\n");
        this.save("        "+t15+"=p+1;\n");
        this.save("        "+t17+"=stack["+t15+"];\n");
        this.save("        "+t18+"="+t17+"/10;\n");
        this.save("        stack["+t15+"]="+t18+";\n");
        this.save("        "+t19+"=p+1;\n");
        this.save("        "+t20+"=p+5;\n");
        this.save("        "+t21+"="+t20+"+1;\n");
        this.save("        "+t22+"=p+1;\n");
        this.save("        "+t23+"=stack["+t22+"];\n");
        this.save("        stack["+t21+"]="+t23+";\n");
        this.save("        p=p+5;\n");
        this.save("        call getent();\n");
        this.save("        "+t24+"=p+0;\n");
        this.save("        "+t25+"=stack["+t24+"];\n");
        this.save("        p=p-5;\n");
        this.save("        $$_clean_scope("+t20+",5);\n");
        this.save("        stack["+t19+"]="+t25+";\n");
        this.save("        goto "+l3+";\n");
        this.save("    "+l5+":\n");
        this.save("    "+l6+":\n");
        this.save("        "+t26+"=p+4;\n");
        this.save("        "+t27+"=stack["+t26+"];\n");
        this.save("        "+t28+"=p+2;\n");
        this.save("        "+t29+"=stack["+t28+"];\n");
        this.save("        if("+t27+"<"+t29+") goto "+l7+";\n");
        this.save("        goto "+l8+";\n");
        this.save("    "+l7+":\n");
        this.save("        heap[h]=48;\n");
        this.save("        h=h+1;\n");
        this.save("        "+t30+"=p+4;\n");
        this.save("        "+t32+"=stack["+t30+"];\n");
        this.save("        "+t33+"="+t32+"+1;\n");
        this.save("        stack["+t30+"]="+t33+";\n");
        this.save("        goto "+l6+";\n");
        this.save("    "+l8+":\n");
        this.save("        "+t34+"=p+5;\n");
        this.save("        "+t35+"="+t34+"+1;\n");
        this.save("        "+t36+"=p+3;\n");
        this.save("        "+t37+"=stack["+t36+"];\n");
        this.save("        stack["+t35+"]="+t37+";\n");
        this.save("        "+t38+"="+t34+"+2;\n");
        this.save("        "+t39+"=p+4;\n");
        this.save("        "+t40+"=stack["+t39+"];\n");
        this.save("        stack["+t38+"]="+t40+";\n");
        this.save("        p=p+5;\n");
        this.save("        call reverse();\n");
        this.save("        p=p-5;\n");
        this.save("        $$_clean_scope("+t34+", 5);\n");
        this.save("        "+t43+"=p+0;\n");
        this.save("        "+t44+"=p+4;\n");
        this.save("        "+t45+"=stack["+t44+"];\n");
        this.save("        stack["+t43+"]="+t45+";\n");
        this.save("}\n");
    }

    getftoa()
    {
        
        var t3=valores.getTemporal();var t4=valores.getTemporal();var t5=valores.getTemporal();
        var t6=valores.getTemporal();var t7=valores.getTemporal();var t8=valores.getTemporal();
        var t9=valores.getTemporal();var t10=valores.getTemporal();var t11=valores.getTemporal();
        var t12=valores.getTemporal();var t13=valores.getTemporal();var t14=valores.getTemporal();
        var t15=valores.getTemporal();var t16=valores.getTemporal();var t17=valores.getTemporal();
        var t18=valores.getTemporal();var t19=valores.getTemporal();var t20=valores.getTemporal();
        var t21=valores.getTemporal();var t22=valores.getTemporal();var t23=valores.getTemporal();
        var t24=valores.getTemporal();var t25=valores.getTemporal();var t26=valores.getTemporal();
        var t27=valores.getTemporal();var t28=valores.getTemporal();var t29=valores.getTemporal();
        var t30=valores.getTemporal();var t31=valores.getTemporal();var t32=valores.getTemporal();
        var t33=valores.getTemporal();var t34=valores.getTemporal();var t35=valores.getTemporal();
        var t36=valores.getTemporal();var t37=valores.getTemporal();var t38=valores.getTemporal();
        var t39=valores.getTemporal();var t40=valores.getTemporal();var t41=valores.getTemporal();
        var t42=valores.getTemporal();var t43=valores.getTemporal();var t44=valores.getTemporal();
        var t45=valores.getTemporal();var t46=valores.getTemporal();var t47=valores.getTemporal();
        var t48=valores.getTemporal();var t49=valores.getTemporal();var t50=valores.getTemporal();
        var t51=valores.getTemporal();var t52=valores.getTemporal();
        var t53=valores.getTemporal();var t54=valores.getTemporal();
        var t55=valores.getTemporal();var t56=valores.getTemporal();
        var t57=valores.getTemporal();var t58=valores.getTemporal();
        var t59=valores.getTemporal();var t60=valores.getTemporal();
        var t61=valores.getTemporal();var t62=valores.getTemporal();
        var t63=valores.getTemporal();var t64=valores.getTemporal();
        var t65=valores.getTemporal();var t66=valores.getTemporal();
        var t67=valores.getTemporal();var t68=valores.getTemporal();
        var t69=valores.getTemporal();var t70=valores.getTemporal();
        var t71=valores.getTemporal();
        /*var l1=valores.getEtiqueta();var l2=valores.getEtiqueta();
        var l3=valores.getEtiqueta();var l4=valores.getEtiqueta();*/
        var l5=valores.getEtiqueta();var l6=valores.getEtiqueta();
        var l7=valores.getEtiqueta();var l8=valores.getEtiqueta();
        var l9=valores.getEtiqueta();var l10=valores.getEtiqueta();
        var l11=valores.getEtiqueta();var l12=valores.getEtiqueta();
        var l13=valores.getEtiqueta();var l14=valores.getEtiqueta();
        var l15=valores.getEtiqueta();var l16=valores.getEtiqueta();
        this.save("void ftoa(){\n");
        this.save("        "+t3+"=p+3;\n");
        this.save("        stack["+t3+"]=h;\n");
        this.save("        "+t4+"=p+1;\n");
        this.save("        "+t5+"=stack["+t4+"];\n");
        this.save("        if("+t5+"<0) goto "+l6+";\n");
        this.save("        goto "+l7+";\n");
        this.save("    "+l6+":\n");
        this.save("        heap[h]=45;\n");
        this.save("        h=h+1;\n");
        this.save("        "+t6+"=p+1;\n");
        this.save("        "+t7+"=p+1;\n");
        this.save("        "+t8+"=stack["+t7+"];\n");
        this.save("        "+t9+"=-1;\n");
        this.save("        "+t10+"="+t8+"*"+t9+";\n");
        this.save("        stack["+t6+"]="+t10+";\n");
        this.save("        goto "+l5+";\n");
        this.save("    "+l7+":\n");
        this.save("    "+l5+":\n");
        this.save("        "+t11+"=p+4;\n");
        this.save("        "+t12+"=p+4;\n");
        this.save("        "+t13+"="+t12+"+1;\n");
        this.save("        "+t14+"=p+1;\n");
        this.save("        "+t15+"=stack["+t14+"];\n");
        this.save("        stack["+t13+"]="+t15+";\n");
        this.save("        p=p+4;\n");
        this.save("        call getent();\n");
        this.save("        "+t16+"=p+0;\n");
        this.save("        "+t17+"=stack["+t16+"];\n");
        this.save("        p=p-4;\n");
        this.save("        $$_clean_scope("+t12+", 4);\n");
        this.save("        stack["+t11+"]="+t17+";\n");
        this.save("        "+t18+"=p+5;\n");
        this.save("        "+t19+"=p+1;\n");
        this.save("        "+t20+"=stack["+t19+"];\n");
        this.save("        "+t21+"=p+4;\n");
        this.save("        "+t22+"=stack["+t21+"];\n");
        this.save("        "+t23+"="+t20+"-"+t22+";\n");
        this.save("        stack["+t18+"]="+t23+";\n");
        this.save("        "+t24+"=p+4;\n");
        this.save("        "+t25+"=stack["+t24+"];\n");
        this.save("        if("+t25+"==0) goto "+l9+";\n");
        this.save("        goto "+l10+";\n");
        this.save("    "+l9+":\n");
        this.save("        heap[h]=48;\n");
        this.save("        h=h+1;\n");
        this.save("        goto "+l8+";\n");
        this.save("    "+l10+":\n");
        this.save("    "+l8+":\n");
        this.save("        "+t26+"=p+6;\n");
        this.save("        "+t27+"=p+6;\n");
        this.save("        "+t28+"="+t27+"+1;\n");
        this.save("        "+t29+"=p+4;\n");
        this.save("        "+t30+"=stack["+t29+"];\n");
        this.save("        stack["+t28+"]="+t30+";\n");
        this.save("        "+t31+"="+t27+"+2;\n");
        this.save("        stack["+t31+"]=0;\n");
        this.save("        p=p+6;\n");
        this.save("        call inttostr();\n");
        this.save("        "+t32+"=p+0;\n");
        this.save("        "+t33+"=stack["+t32+"];\n");
        this.save("        p=p-6;\n");
        this.save("        $$_clean_scope("+t27+", 6);\n");
        this.save("        stack["+t26+"]="+t33+";\n");
        this.save("        "+t34+"=p+2;\n");
        this.save("        "+t35+"=stack["+t34+"];\n");
        this.save("        if ("+t35+"!=0) goto "+l12+";\n");
        this.save("        goto "+l13+";\n");
        this.save("    "+l12+":\n");
        this.save("        heap[h]=46;\n");
        this.save("        h=h+1;\n");
        this.save("        "+t36+"=p+7;\n");
        this.save("        stack["+t36+"]=0;\n");
        this.save("        "+t37+"=p+8;\n");
        this.save("        stack["+t37+"]=1;\n");
        this.save("    "+l14+":\n");
        this.save("        "+t38+"=p+7;\n");
        this.save("        "+t39+"=stack["+t38+"];\n");
        this.save("        "+t40+"=p+2;\n");
        this.save("        "+t41+"=stack["+t40+"];\n");
        this.save("        if("+t39+"<"+t41+") goto "+l15+";\n");
        this.save("        goto "+l16+";\n");
        this.save("    "+l15+":\n");
        this.save("        "+t42+"=p+8;\n");
        this.save("        "+t43+"=p+8;\n");
        this.save("        "+t44+"=stack["+t43+"];\n");
        this.save("        "+t45+"="+t44+"*10;\n");
        this.save("        stack["+t42+"]="+t45+";\n");
        this.save("        "+t46+"=p+7;\n");
        this.save("        "+t47+"=p+7;\n");
        this.save("        "+t48+"=stack["+t47+"];\n");
        this.save("        "+t49+"="+t48+"+1;\n");
        this.save("        stack["+t46+"]="+t49+";\n");
        this.save("        goto "+l14+";\n");
        this.save("    "+l16+":\n");
        this.save("        "+t50+"=p+5;\n");
        this.save("        "+t51+"=p+5;\n");
        this.save("        "+t52+"=stack["+t51+"];\n");
        this.save("        "+t53+"=p+8;\n");
        this.save("        "+t54+"=stack["+t53+"];\n");
        this.save("        "+t55+"="+t52+"*"+t54+";\n");
        this.save("        stack["+t50+"]="+t55+";\n");
        this.save("        "+t56+"=p+10;\n");
        this.save("        "+t57+"="+t56+"+1;\n");
        this.save("        "+t58+"=p+10;\n");
        this.save("        "+t59+"="+t58+"+1;\n");
        this.save("        "+t60+"=p+5;\n");
        this.save("        "+t61+"=stack["+t60+"];\n");
        this.save("        stack["+t59+"]="+t61+";\n");
        this.save("        p=p+10;\n");
        this.save("        call getent();\n");
        this.save("        "+t62+"=p+0;\n");
        this.save("        "+t63+"=stack["+t62+"];\n");
        this.save("        p=p-10;\n");
        this.save("        $$_clean_scope("+t58+",10);\n");
        this.save("        stack["+t57+"]="+t63+";\n");
        this.save("        "+t64+"="+t56+"+2;\n");
        this.save("        "+t65+"=p+2;\n");
        this.save("        "+t66+"=stack["+t65+"];\n");
        this.save("        stack["+t64+"]="+t66+";\n");
        this.save("        p=p+10;\n");
        this.save("        call inttostr();\n");
        this.save("        "+t67+"=p+0;\n");    
        this.save("        "+t68+"=stack["+t67+"];\n");
        this.save("        p=p-10;\n");
        this.save("        goto "+l11+";\n");
        this.save("    "+l13+":\n");
        this.save("    "+l11+":\n");
        this.save("        heap[h]="+tablaTipos.fin_cadena+";\n");
        this.save("        h=h+1;\n");
        this.save("        "+t69+"=p+0;\n");
        this.save("        "+t70+"=p+3;\n");
        this.save("        "+t71+"=stack["+t70+"];\n");
        this.save("        stack["+t69+"]="+t71+";\n");
        this.save("}\n");
    }
    
}

module.exports = traducir;